In [1]:
import numpy as np
import pickle

In [2]:
KG_VECTORS_2 = pickle.load(open("../wordEmbeddings/KG_VECTORS_2.pickle", "rb"))

In [3]:
for key in KG_VECTORS_2:
    print(key, len(KG_VECTORS_2[key]))

/c/en/company 21267
/c/en/education 7514
/c/en/artist 7035
/c/en/athlete 5156
/c/en/officer 12797
/c/en/transport 14151
/c/en/building 34099
/c/en/nature 24775
/c/en/village 11549
/c/en/animal 62420
/c/en/plant 46970
/c/en/album 5381
/c/en/film 15207
/c/en/writing 18824


In [2]:
data = np.load('../results/test_5.npz')

In [3]:
print(data.keys())

['align_unseen', 'gt_seen', 'pred_unseen', 'align_seen', 'pred_seen', 'gt_unseen']


In [5]:
print(data['gt_unseen'], data['pred_unseen'], data['align_unseen'])

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]] [[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]] [[[2.47972156e-03 2.73659639e-03 2.02324498e-03 ... 3.87769453e-02
   9.77866575e-02 9.69534069e-02]
  [9.36909858e-03 9.62136686e-03 7.42427306e-03 ... 2.30694991e-02
   2.38265380e-01 3.20462227e-01]
  [2.78055595e-05 3.19405553e-05 2.46378622e-05 ... 4.07097396e-04
   5.02543598e-02 9.46804345e-01]
  ...
  [1.32638263e-03 1.42502296e-03 1.00284070e-03 ... 2.21102890e-02
   7.81787410e-02 7.99784884e-02]
  [5.52700879e-03 5.93346125e-03 4.26079705e-03 ... 2.06842422e-02
   1.01126134e-01 1.16921619e-01]
  [6.46062428e-04 6.23823900e-04 4.90807986e-04 ... 2.92846859e-02
   1.86704919e-01 2.34603584e-01]]

 [[6.90063986e-04 9.84093989e-04 1.23169867e-03 ... 3.82701159e-02
   3.81